---
deployment:
  tasks:
    - export DEPLOYPATH=/home/public_html/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp ecosystem.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp prisma $DEPLOYPATH 